/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/00-sidebar': RouteRecordInfo<'/00-sidebar', '/00-sidebar', Record<never, never>, Record<never, never>>,
    '/01-body': RouteRecordInfo<'/01-body', '/01-body', Record<never, never>, Record<never, never>>,
    '/03-grid': RouteRecordInfo<'/03-grid', '/03-grid', Record<never, never>, Record<never, never>>,
    '/04-random-tests': RouteRecordInfo<'/04-random-tests', '/04-random-tests', Record<never, never>, Record<never, never>>,
    '/05-destroy': RouteRecordInfo<'/05-destroy', '/05-destroy', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/00-sidebar.vue': {
      routes: '/00-sidebar'
      views: never
    }
    'src/pages/01-body.vue': {
      routes: '/01-body'
      views: never
    }
    'src/pages/03-grid.vue': {
      routes: '/03-grid'
      views: never
    }
    'src/pages/04-random-tests.vue': {
      routes: '/04-random-tests'
      views: never
    }
    'src/pages/05-destroy.vue': {
      routes: '/05-destroy'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
