packages:
  - 'apps/*'
  - 'packages/*'
  - '!**/test/**'

catalogs:
  vue2:
    '@vue/compiler-sfc': ^2.7.16
    '@vue/test-utils': ^1.3.6
    vue: ^2.7.16
    vue-router: ^3.6.5
  vue3:
    '@vue/compiler-sfc': ^3.5.20
    '@vue/test-utils': ^2.4.6
    vue: ^3.5.20
    vue-router: ^4.5.1
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
